Incrementing the version number to 0.24.0
PennyLaneAI/pennylane-lightning-gpu pull request #31
Opened 2022-06-15 19:18 UTC by trevor-vincent

Release candidate v0.24 for pennylane-lightning-gpu.

2022-06-15 19:57 UTC, AmintorDusko commented on pennylane_lightning_gpu/_version.py
> +__version__ = "0.24.0"
```suggestion
__version__ = "0.24.0-rc0"
```

2022-06-15 20:38 UTC, mlxd commented on pennylane_lightning_gpu/_version.py
> +__version__ = "0.24.0"
Keep this around until we release.

2022-06-17 18:47 UTC, mlxd requested changes

2022-06-17 18:47 UTC, mlxd commented on .github/CHANGELOG.md
> +---
We shouldn't have the 0.25 dev notes here. That should only go into the main branch once we are done.

2022-06-17 18:47 UTC, mlxd commented on .github/CHANGELOG.md
> +### Breaking changes
I think the update to C++20 is a breaking change for those with older tooling. Worth a mention?

2022-06-17 18:51 UTC, AmintorDusko commented on pennylane_lightning_gpu/src/tests/Test_StateVectorCudaManaged_Param.cpp
> +              Pennylane::approx(svdat_expected.sv.getDataVector()));
So many of these changes. Good job.

2022-06-20 13:12 UTC, mlxd requested changes
Those changes should be good to make for the release.

2022-06-20 13:12 UTC, mlxd commented on CMakeLists.txt
> +    GIT_TAG        v0.24_rc0
```suggestion
    GIT_TAG       latest
```

2022-06-20 13:12 UTC, mlxd commented on pennylane_lightning_gpu/_version.py
> +__version__ = "0.24.0-rc0"
```suggestion
__version__ = "0.24.0"
```

2022-06-20 15:28 UTC, mlxd commented on .github/CHANGELOG.md
> +Ali Asadi,  Amintor Dusko, Chae-Yeun Park, Lee James O'Riordan, and Trevor Vincent
```suggestion
Ali Asadi, Amintor Dusko, Chae-Yeun Park, Lee James O'Riordan, and Trevor Vincent
```

2022-06-20 18:32 UTC, merged