add header "unordered_map" to util/cuda_helpers.hpp
PennyLaneAI/pennylane-lightning-gpu pull request #86
Opened 2023-01-03 03:02 UTC by fwcore

Prevent compilation error for g++-11

**Context:**
When compiling this repo in a docker `pytorch/pytorch`:
* ubuntu version 18.04
* gcc version 11 (installed from ppa:ubuntu-toolchain-r/test)
* nvcc/CUDA version 11.7

This line
https://github.com/PennyLaneAI/pennylane-lightning-gpu/blob/1efbe63881aeed132e3f38d31f5ad4bf26186722/pennylane_lightning_gpu/src/util/cuda_helpers.hpp#L589 fails to compile.

**Description of the Change:**

Add missing header `<unordered_map>` to util/cuda_helpers.hpp

**Benefits:**

The above file compiles.

**Possible Drawbacks:**

**Related GitHub Issues:**

2023-01-03 19:57 UTC, multiphaseCFD commented
Hi @fwcore, Thanks for reporting this bug and the fix!

2023-01-03 20:00 UTC, AmintorDusko requested changes
Thank you for the fix. Could you please fill out the changelog file?
You can find it [here](https://github.com/PennyLaneAI/pennylane-lightning-gpu/blob/main/.github/CHANGELOG.md).
Don't forget to add your name to the contributors' list.

2023-01-04 11:02 UTC, fwcore commented
> Hi @fwcore, Thanks for reporting this bug and the fix! Could you please share the compilation errors? Thanks

Here is the relevant error message:
```
/workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(589): error: expected a ";"
/workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(597): warning: parsing restarts here after previous syntax error
/workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(605): error: identifier "pauli_map" is undefined
```

2023-01-04 11:07 UTC, fwcore commented
Thanks for reviewing the PR. I have updated the CHANGELOG.md. Please review again. Thanks.

2023-01-04 14:39 UTC, multiphaseCFD commented on .github/CHANGELOG.md
> +* add header "unordered_map" to util/cuda_helpers.hpp [(#86)](https://github.com/PennyLaneAI/pennylane-lightning-gpu/pull/86)
```suggestion
* Add header `unordered_map` to `util/cuda_helpers.hpp`.
 [(#86)](https://github.com/PennyLaneAI/pennylane-lightning-gpu/pull/86)
```

2023-01-04 14:40 UTC, multiphaseCFD commented on .github/CHANGELOG.md
> +
```suggestion
```

2023-01-04 14:42 UTC, multiphaseCFD commented
> > Hi @fwcore, Thanks for reporting this bug and the fix! Could you please share the compilation errors? Thanks
> 
> Here is the relevant error message:
> 
> ```
> /workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(589): error: expected a ";"
> /workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(597): warning: parsing restarts here after previous syntax error
> /workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(605): error: identifier "pauli_map" is undefined
> ```

Thanks @fwcore for sharing the information. Just some additional comments on typo of `changelog`.

2023-01-06 12:04 UTC, fwcore commented
> > > Hi @fwcore, Thanks for reporting this bug and the fix! Could you please share the compilation errors? Thanks
> > 
> > 
> > Here is the relevant error message:
> > ```
> > /workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(589): error: expected a ";"
> > /workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(597): warning: parsing restarts here after previous syntax error
> > /workspace/pennylane-lightning-gpu/pennylane_lightning_gpu/src/util/cuda_helpers.hpp(605): error: identifier "pauli_map" is undefined
> > ```
> 
> Thanks @fwcore for sharing the information. Just some additional comments on typo of `changelog`.

Sorry for the late reply.

Thanks @multiphaseCFD for the suggestions. Please check again for the new commit. Thanks.

2023-01-06 14:38 UTC, AmintorDusko approved these changes
Thank you @fwcore for your nice work!

2023-01-06 14:40 UTC, merged

2023-01-07 06:38 UTC, fwcore commented
Thank you all. Have a nice day.